# -*- coding: utf-8 -*-
# Fila de artigos (pauta) para publicacao automatica diaria.
# O estado de "publicado" e a propria existencia do arquivo {slug}.html no repo.
# publicar.py pega os proximos que ainda nao existem, na ordem desta lista.
# REGRA DE ESTILO: nunca usar travessao longo. Usar virgula ou parenteses.

CATS = {
 'saude': ('Saúde da Mulher','saude da mulher hormônios mulher ciclo'),
 'materno': ('Materno-infantil','bebê criança infantil filho materno introdução alimentar'),
 'emagrecimento': ('Emagrecimento','emagrecer perder peso dieta'),
 'esportiva': ('Nutrição Esportiva','treino músculo proteína academia hipertrofia'),
 'bemestar': ('Saúde & Bem-estar','saúde intestino bem-estar metabolismo'),
}

ARTICLES = [
 {'slug':'gordura-no-figado','read':7,'cat':'bemestar','badge':'Dá pra reverter',
  'title':'Gordura no fígado: o que comer para reverter',
  'desc':'A gordura no fígado tem tratamento e a alimentação é a parte principal. Veja o que ajuda a reverter e o que piora o quadro.',
  'lead':'A esteatose hepática, mais conhecida como gordura no fígado, é hoje uma das alterações mais comuns nos exames de rotina. A boa notícia é que, na maioria dos casos, ela é reversível, e a alimentação é justamente o pilar do tratamento.',
  'body':[
    ('h2','Por que a gordura se acumula no fígado'),
    ('p','O acúmulo de gordura no fígado costuma estar ligado ao excesso de peso, ao consumo alto de açúcar e ultraprocessados e à resistência à insulina. O fígado passa a estocar gordura quando recebe mais energia do que consegue processar.'),
    ('quote','Gordura no fígado quase sempre é um recado do corpo sobre o estilo de vida, e responde muito bem quando a gente escuta esse recado.'),
    ('h2','O que ajuda a reverter'),
    ('h3','No prato'),
    ('p','Priorizar comida de verdade faz diferença rápida: verduras, legumes, frutas, grãos integrais, proteínas magras e boas fontes de gordura como azeite, castanhas e peixes. Reduzir açúcar, farinha branca e alimentos ultraprocessados alivia o trabalho do fígado.'),
    ('h3','Além do prato'),
    ('p','A perda de peso, mesmo que gradual, reduz a gordura hepática de forma consistente. A atividade física regular também melhora a sensibilidade à insulina, o que ajuda a esvaziar o estoque de gordura do fígado.'),
    ('keybox','Passos que revertem a gordura no fígado',['Reduzir açúcar, refrigerante e alimentos ultraprocessados.','Aumentar verduras, legumes, frutas e grãos integrais.','Perder peso de forma gradual e sustentável.','Incluir atividade física na rotina, mesmo caminhadas.','Evitar bebida alcoólica, que sobrecarrega o fígado.']),
    ('h2','Quando buscar acompanhamento'),
    ('p','Se o exame apontou gordura no fígado, vale investigar com acompanhamento médico e nutricional para entender a causa e montar um plano individualizado. Com ajustes consistentes na alimentação e na rotina, a maioria das pessoas consegue reverter o quadro.'),
  ],
  'faq':[('Gordura no fígado tem cura?','Na maioria dos casos sim, principalmente nas fases iniciais. Com mudança na alimentação, perda de peso e atividade física, o fígado costuma se recuperar.'),
         ('Quanto tempo leva para reverter?','Varia de pessoa para pessoa, mas melhoras já aparecem em alguns meses de mudança consistente. O acompanhamento ajuda a monitorar a evolução.'),
         ('Preciso cortar carboidrato por completo?','Não. O foco é reduzir açúcar e ultraprocessados e priorizar carboidratos integrais em porções adequadas, não eliminar o grupo inteiro.')]},

 {'slug':'pressao-alta-alimentacao','read':7,'cat':'bemestar','badge':'Aliada do coração',
  'title':'Pressão alta: como a alimentação ajuda a controlar',
  'desc':'A alimentação tem papel direto no controle da pressão arterial. Veja o que reduzir, o que incluir e como o prato ajuda o coração.',
  'lead':'A pressão alta é silenciosa e muito comum, e a alimentação é uma das ferramentas mais poderosas para mantê-la sob controle, muitas vezes potencializando ou até reduzindo a necessidade de medicação, sempre com acompanhamento médico.',
  'body':[
    ('h2','O sódio é o vilão principal'),
    ('p','O excesso de sódio faz o corpo reter líquido e aumenta a pressão sobre as artérias. A maior parte do sódio que consumimos não vem do saleiro, mas de alimentos ultraprocessados como embutidos, temperos prontos, enlatados e salgadinhos.'),
    ('quote','Controlar a pressão passa muito menos por tirar o sal da mesa e muito mais por sair dos ultraprocessados.'),
    ('h2','O que colocar no prato'),
    ('h3','Alimentos que ajudam'),
    ('p','Frutas, verduras e legumes são ricos em potássio, mineral que equilibra os efeitos do sódio. Grãos integrais, feijões, oleaginosas e laticínios magros também fazem parte de um padrão alimentar que protege o coração.'),
    ('h3','O que reduzir'),
    ('p','Vale reduzir embutidos, defumados, temperos industrializados, caldos prontos, refrigerantes e o excesso de álcool. Ler o rótulo e observar a quantidade de sódio ajuda muito nas escolhas do dia a dia.'),
    ('keybox','Hábitos que ajudam a controlar a pressão',['Reduzir ultraprocessados, embutidos e temperos prontos.','Aumentar frutas, verduras e legumes ricos em potássio.','Temperar com ervas, alho e limão no lugar de sal.','Manter o peso adequado e praticar atividade física.','Moderar álcool e não fumar.']),
    ('h2','Alimentação e remédio caminham juntos'),
    ('p','A comida não substitui o tratamento prescrito, mas potencializa os resultados e pode, em alguns casos, reduzir a dose necessária, sempre sob orientação. Um plano alimentar individualizado ajuda a controlar a pressão sem tornar as refeições sem graça.'),
  ],
  'faq':[('Só cortar o sal resolve?','Ajuda, mas o maior impacto vem de reduzir alimentos ultraprocessados, que concentram a maior parte do sódio da dieta.'),
         ('Posso usar sal light?','Pode ser uma opção para algumas pessoas, mas ele contém potássio e não é indicado para quem tem problemas renais. O ideal é orientar caso a caso.'),
         ('Café aumenta a pressão?','O café pode elevar a pressão de forma passageira, mas o consumo moderado costuma ser bem tolerado. Vale observar a resposta individual.')]},

 {'slug':'imunidade-alimentacao','read':6,'cat':'bemestar','badge':'Sem fórmula mágica',
  'title':'Imunidade: os alimentos que realmente ajudam',
  'desc':'Nenhum alimento sozinho blinda o corpo, mas a alimentação faz diferença real na imunidade. Veja o que funciona de verdade.',
  'lead':'Toda estação mais fria reacende a busca por alimentos que aumentam a imunidade. A verdade é que nenhum ingrediente isolado faz milagre, mas o conjunto da alimentação tem sim um papel importante na defesa do organismo.',
  'body':[
    ('h2','Imunidade não se constrói em um dia'),
    ('p','O sistema imune depende de vários nutrientes trabalhando juntos ao longo do tempo. Por isso, mais importante do que um alimento específico é a qualidade geral da alimentação na rotina.'),
    ('quote','Imunidade não vem de um suco milagroso, vem do que você come na maior parte dos seus dias.'),
    ('h2','Nutrientes que fazem diferença'),
    ('h3','Onde encontrar'),
    ('p','Vitamina C está em frutas cítricas, goiaba e pimentão. Zinco aparece em carnes, ovos, feijões e sementes. Vitamina A vem de vegetais alaranjados e verde-escuros. O selênio da castanha-do-pará também tem seu papel.'),
    ('h3','O intestino também importa'),
    ('p','Boa parte das células de defesa está no intestino, então uma alimentação rica em fibras, com frutas, verduras, legumes e grãos integrais, sustenta uma microbiota saudável e favorece a imunidade.'),
    ('keybox','Para uma imunidade mais forte',['Variar frutas, verduras e legumes de cores diferentes.','Garantir boas fontes de proteína ao longo do dia.','Cuidar do intestino com fibras e alimentos naturais.','Reduzir ultraprocessados, açúcar e álcool.','Dormir bem e manter-se hidratado, o resto é consequência.']),
    ('h2','E os suplementos?'),
    ('p','Suplementar só faz sentido quando há uma deficiência identificada, e não como estratégia geral. Antes de gastar com cápsulas, vale ajustar a alimentação. Um acompanhamento nutricional identifica o que realmente falta no seu caso.'),
  ],
  'faq':[('Vitamina C previne gripe?','A vitamina C ajuda no funcionamento do sistema imune, mas não previne gripes por si só. O efeito vem do conjunto da alimentação e dos hábitos.'),
         ('Preciso tomar suplemento para imunidade?','Só se houver uma deficiência comprovada. Para a maioria das pessoas, uma alimentação variada supre o necessário.'),
         ('Alho e gengibre aumentam a imunidade?','Eles têm compostos interessantes e podem fazer parte da alimentação, mas não substituem uma dieta equilibrada como um todo.')]},

 {'slug':'enxaqueca-alimentos-gatilho','read':7,'cat':'bemestar','badge':'Identifique os gatilhos',
  'title':'Enxaqueca: alimentos que podem ser gatilho',
  'desc':'Alguns alimentos podem disparar crises de enxaqueca em pessoas sensíveis. Veja os principais suspeitos e como identificar os seus.',
  'lead':'Quem sofre de enxaqueca sabe o quanto uma crise atrapalha o dia. A alimentação não é a causa da enxaqueca, mas certos alimentos podem funcionar como gatilho em pessoas mais sensíveis, e identificá-los ajuda a reduzir a frequência das crises.',
  'body':[
    ('h2','Por que alguns alimentos disparam crises'),
    ('p','Alguns alimentos contêm substâncias que, em pessoas predispostas, podem influenciar os vasos sanguíneos e os neurotransmissores ligados à enxaqueca. A sensibilidade varia muito de pessoa para pessoa.'),
    ('quote','O gatilho de uma pessoa pode ser inofensivo para outra. Por isso, observar a sua própria resposta vale mais do que uma lista pronta.'),
    ('h2','Suspeitos mais comuns'),
    ('h3','Fique de olho'),
    ('p','Entre os gatilhos frequentemente relatados estão queijos amarelos curados, embutidos, chocolate, cafeína em excesso, bebida alcoólica (em especial vinho tinto) e alimentos ricos em glutamato, comum em ultraprocessados.'),
    ('h3','O jejum também conta'),
    ('p','Ficar muitas horas sem comer e a desidratação são gatilhos importantes e às vezes esquecidos. Manter refeições regulares e boa hidratação já ajuda bastante a prevenir crises.'),
    ('keybox','Como identificar seus gatilhos',['Manter um diário de alimentação e crises por algumas semanas.','Observar o padrão, não apenas o alimento da última refeição.','Evitar ficar longos períodos sem comer.','Cuidar da hidratação ao longo do dia.','Testar mudanças com orientação, sem cortar tudo de uma vez.']),
    ('h2','Nem sempre é a comida'),
    ('p','Sono irregular, estresse e alterações hormonais também influenciam as crises, então nem todo episódio tem relação com a alimentação. Um acompanhamento ajuda a identificar padrões sem restringir alimentos sem necessidade.'),
  ],
  'faq':[('Existe uma dieta que cura a enxaqueca?','Não existe cura pela dieta, mas identificar e reduzir gatilhos individuais ajuda a diminuir a frequência e a intensidade das crises.'),
         ('Chocolate sempre causa enxaqueca?','Não para todo mundo. Para algumas pessoas é gatilho, para outras não. Vale observar a própria resposta antes de cortar.'),
         ('Cafeína ajuda ou atrapalha?','Depende. Em pequenas doses pode ajudar em algumas crises, mas o excesso e a abstinência costumam piorar. O equilíbrio é individual.')]},

 {'slug':'barriga-inchada-o-que-pode-ser','read':7,'cat':'bemestar','badge':'Desinchar de verdade',
  'title':'Barriga inchada: o que pode ser e como desinchar',
  'desc':'A barriga inchada quase sempre tem explicação. Veja as causas mais comuns e o que realmente ajuda a desinchar no dia a dia.',
  'lead':'Poucas queixas são tão comuns quanto a barriga inchada, aquela sensação de estufamento que aparece principalmente no fim do dia. Na maioria das vezes ela tem causas simples ligadas à digestão e aos hábitos, não a um problema grave.',
  'body':[
    ('h2','O que costuma causar o inchaço'),
    ('p','O inchaço abdominal geralmente vem de gases, digestão lenta, comer rápido demais, excesso de alimentos que fermentam ou intestino preso. O excesso de sódio e a retenção de líquido também contribuem para a sensação de estufamento.'),
    ('quote','Barriga inchada quase sempre é um sinal de digestão sobrecarregada, não de gordura acumulada de um dia para o outro.'),
    ('h2','O que ajuda a desinchar'),
    ('h3','Ajustes na rotina'),
    ('p','Comer com calma e mastigar bem reduz a entrada de ar e melhora a digestão. Distribuir as refeições, evitar exagerar em uma só e manter o intestino funcionando com fibras e água fazem grande diferença.'),
    ('h3','O que costuma piorar'),
    ('p','Refrigerantes e bebidas com gás, excesso de ultraprocessados, adoçantes em grande quantidade e refeições muito volumosas tendem a aumentar o inchaço em pessoas sensíveis.'),
    ('keybox','Para desinchar no dia a dia',['Comer devagar e mastigar bem os alimentos.','Manter boa hidratação ao longo do dia.','Caprichar em fibras para o intestino funcionar.','Reduzir refrigerante, ultraprocessados e excesso de sódio.','Observar quais alimentos fermentam mais no seu caso.']),
    ('h2','Quando investigar'),
    ('p','Se o inchaço é constante, muito intenso ou vem com outros sintomas, vale investigar com acompanhamento, pois pode envolver intolerâncias ou questões intestinais. Um plano individualizado ajuda a encontrar os gatilhos sem restrições desnecessárias.'),
  ],
  'faq':[('Barriga inchada é gordura?','Geralmente não. O inchaço costuma ser gases, retenção ou digestão lenta, e melhora ao longo do dia ou com ajustes na alimentação.'),
         ('Cortar glúten desincha?','Só ajuda quem tem sensibilidade ou doença celíaca. Para a maioria, o problema está no conjunto dos hábitos, não no glúten em si.'),
         ('Chá desincha mesmo?','A hidratação ajuda, e alguns chás dão sensação de alívio, mas não fazem milagre. O que resolve é o padrão alimentar como um todo.')]},

 {'slug':'low-carb-funciona','read':7,'cat':'emagrecimento','badge':'O que a ciência diz',
  'title':'Dieta low carb funciona mesmo?',
  'desc':'A dieta low carb emagrece? Entenda como ela funciona, para quem faz sentido e por que não é a única forma de perder peso.',
  'lead':'A dieta low carb é uma das mais populares quando o assunto é emagrecimento. Ela pode sim funcionar, mas entender por que ela funciona ajuda a decidir se faz sentido para você, e a não cair na ideia de que carboidrato é o inimigo.',
  'body':[
    ('h2','Como a low carb funciona'),
    ('p','Reduzir carboidratos costuma diminuir naturalmente as calorias do dia, já que muitos alimentos calóricos são ricos em carboidrato refinado. Além disso, mais proteína e gordura aumentam a saciedade, o que ajuda a comer menos sem tanta fome.'),
    ('quote','Nenhuma dieta emagrece por mágica. A low carb funciona quando ajuda você a comer menos e com mais saciedade.'),
    ('h2','Para quem faz sentido'),
    ('h3','Pode ajudar'),
    ('p','Pessoas com resistência à insulina, muita fome ao longo do dia ou que se adaptam bem a menos carboidrato podem se beneficiar. O importante é manter proteína adequada, fibras e boas fontes de gordura.'),
    ('h3','Nem sempre é a melhor escolha'),
    ('p','Quem treina pesado, gosta de carboidrato e mantém o peso com uma dieta equilibrada não precisa cortar o grupo. Restrições muito rígidas são difíceis de sustentar e podem levar ao efeito sanfona.'),
    ('keybox','Se for testar a low carb',['Manter proteína adequada em todas as refeições.','Não abandonar fibras: verduras, legumes e sementes.','Priorizar boas gorduras como azeite, castanhas e abacate.','Não cortar carboidrato a zero sem necessidade.','Escolher um formato que você consiga manter a longo prazo.']),
    ('h2','A melhor dieta é a que você mantém'),
    ('p','A low carb é uma ferramenta entre várias, não a única forma de emagrecer. O que decide o resultado é a aderência ao longo do tempo. Um plano individualizado define se ela faz sentido para o seu objetivo e rotina.'),
  ],
  'faq':[('Low carb emagrece mais rápido?','No início pode parecer, em parte pela perda de água. No médio prazo, o resultado depende do balanço calórico e da aderência, como em qualquer dieta.'),
         ('Preciso cortar todo carboidrato?','Não. Low carb significa reduzir, não zerar. Verduras, legumes e algumas frutas continuam fazendo parte.'),
         ('Posso treinar fazendo low carb?','Pode, mas quem treina intenso costuma render melhor com algum carboidrato. Vale ajustar a quantidade ao tipo de treino.')]},

 {'slug':'emagrecer-depois-dos-40','read':7,'cat':'emagrecimento','badge':'Realista e possível',
  'title':'Como emagrecer depois dos 40',
  'desc':'Emagrecer depois dos 40 é possível, mas pede estratégia. Veja o que muda no corpo e como ajustar a alimentação e a rotina.',
  'lead':'Muita gente sente que emagrecer fica mais difícil depois dos 40, e não é impressão. Algumas mudanças no corpo realmente entram em jogo, mas com a estratégia certa é totalmente possível perder peso e, principalmente, manter.',
  'body':[
    ('h2','O que muda a partir dos 40'),
    ('p','Com o passar dos anos, é comum perder massa muscular, o que reduz o gasto de energia em repouso. Alterações hormonais, mais estresse e menos tempo para se cuidar também influenciam. O metabolismo não trava, mas responde a esse conjunto.'),
    ('quote','Depois dos 40 o corpo não vira as costas para você, ele só pede mais cuidado com músculo, proteína e sono.'),
    ('h2','O que priorizar'),
    ('h3','Proteína e músculo'),
    ('p','Garantir proteína suficiente e fazer musculação ajudam a preservar e ganhar massa muscular, o que sustenta o metabolismo. Esse é um dos pontos mais importantes nessa fase e costuma ser negligenciado.'),
    ('h3','Comida de verdade e constância'),
    ('p','Priorizar comida de verdade, controlar ultraprocessados e manter uma rotina possível vale mais do que dietas radicais. A constância é o que traz resultado duradouro depois dos 40.'),
    ('keybox','Estratégias para emagrecer depois dos 40',['Garantir proteína em todas as refeições.','Incluir musculação para preservar massa muscular.','Priorizar comida de verdade e reduzir ultraprocessados.','Cuidar do sono e do estresse, que afetam o peso.','Buscar constância em vez de dietas radicais.']),
    ('h2','Paciência e acompanhamento'),
    ('p','O ritmo pode ser um pouco mais lento, e tudo bem. O foco deve ser em saúde e sustentabilidade, não em pressa. Um acompanhamento nutricional ajusta a estratégia às mudanças dessa fase e evita o efeito sanfona.'),
  ],
  'faq':[('O metabolismo trava depois dos 40?','Não trava, mas tende a desacelerar, muito por causa da perda de massa muscular. Musculação e proteína ajudam a manter o gasto energético.'),
         ('Preciso comer bem menos para emagrecer?','Não se trata de passar fome, e sim de ajustar a qualidade e a quantidade. Comer pouco demais pode até atrapalhar preservando pouco músculo.'),
         ('Menopausa impede o emagrecimento?','Não impede, mas muda o cenário hormonal. Com estratégia adequada, é possível emagrecer e melhorar a composição corporal.')]},

 {'slug':'beliscar-entre-refeicoes','read':6,'cat':'emagrecimento','badge':'Quebre o ciclo',
  'title':'Beliscar entre as refeições: como parar',
  'desc':'Beliscar o tempo todo sabota o emagrecimento sem você perceber. Veja por que isso acontece e como quebrar o hábito.',
  'lead':'Aquela beliscada aqui e ali parece inofensiva, mas somada ao longo do dia pode sabotar o emagrecimento sem que você perceba. Entender por que a gente belisca é o primeiro passo para quebrar o ciclo.',
  'body':[
    ('h2','Por que a gente belisca'),
    ('p','Beliscar raramente é só fome. Muitas vezes está ligado a refeições mal montadas que não saciam, longos períodos sem comer que geram compensação, ansiedade, tédio ou o simples hábito de ter comida por perto.'),
    ('quote','Quem come bem nas refeições principais quase não sente vontade de beliscar depois.'),
    ('h2','Como reduzir o hábito'),
    ('h3','Refeições que saciam'),
    ('p','Montar pratos com proteína, fibras e boas gorduras aumenta a saciedade e reduz a vontade de beliscar entre as refeições. Comer com atenção, sem tela, também ajuda o corpo a reconhecer que já comeu.'),
    ('h3','Organizar o ambiente'),
    ('p','Deixar ultraprocessados fora do campo de visão e ter opções melhores à mão muda muito o comportamento. Se a beliscada é emocional, vale identificar o gatilho antes de partir para a comida.'),
    ('keybox','Para parar de beliscar',['Montar refeições que realmente saciam, com proteína e fibras.','Não pular refeições nem ficar horas sem comer.','Comer com atenção, longe de telas.','Tirar os ultraprocessados do alcance dos olhos.','Identificar se a fome é física ou emocional.']),
    ('h2','Belisco não é falha de caráter'),
    ('p','Beliscar demais quase sempre é sinal de que algo na rotina ou nas refeições precisa de ajuste, não falta de força de vontade. Um acompanhamento ajuda a montar refeições que saciam e a lidar com a fome emocional sem culpa.'),
  ],
  'faq':[('Beliscar engorda mesmo?','Pode engordar quando as beliscadas somam muitas calorias extras no dia sem você perceber. O problema é o acúmulo, não uma beliscada isolada.'),
         ('É melhor fazer várias pequenas refeições?','Depende da pessoa. O que importa é o total do dia e a saciedade. Para muita gente, refeições bem montadas reduzem a necessidade de comer o tempo todo.'),
         ('Como parar de beliscar por ansiedade?','Identificar o gatilho é o primeiro passo. Estratégias que não envolvem comida e, quando preciso, apoio profissional ajudam a lidar com a fome emocional.')]},

 {'slug':'suplementos-para-iniciantes','read':7,'cat':'esportiva','badge':'Comece pelo básico',
  'title':'Suplementos para iniciantes: o que vale a pena',
  'desc':'Começou a treinar e ficou perdido nos suplementos? Veja o que realmente vale a pena para quem está começando.',
  'lead':'Quem começa a treinar logo se depara com uma infinidade de suplementos e promessas. A verdade é que a maioria não é necessária, e poucos itens realmente fazem diferença para quem está começando.',
  'body':[
    ('h2','A base vem primeiro'),
    ('p','Nenhum suplemento substitui uma alimentação adequada, sono e treino consistente. Suplemento é complemento, entra para preencher o que a comida não deu conta, não para carregar o resultado sozinho.'),
    ('quote','Suplemento é a cereja do bolo. Se o bolo (comida, treino e sono) não existe, a cereja não faz diferença.'),
    ('h2','O que costuma valer a pena'),
    ('h3','Os mais respaldados'),
    ('p','Whey protein ajuda a bater a meta de proteína com praticidade. A creatina é um dos suplementos mais estudados e seguros, com benefícios para força e desempenho. Os dois têm boa base científica.'),
    ('h3','O que geralmente é desnecessário'),
    ('p','Termogênicos, BCAA para quem já come proteína suficiente e a maioria dos pré-treinos elaborados costumam ter pouco impacto real para iniciantes. Muitas vezes o dinheiro rende mais em comida de qualidade.'),
    ('keybox','Para quem está começando',['Acertar primeiro alimentação, treino e sono.','Considerar whey apenas se tiver dificuldade de bater a proteína.','Creatina é segura e bem respaldada para desempenho.','Desconfiar de promessas milagrosas e fórmulas caras.','Buscar orientação antes de gastar com vários potes.']),
    ('h2','Individualize as escolhas'),
    ('p','A necessidade de suplemento depende do seu objetivo, da sua rotina e do que já vem da alimentação. Um acompanhamento nutricional evita gasto desnecessário e indica o que realmente faz sentido para o seu caso.'),
  ],
  'faq':[('Preciso tomar whey para ganhar músculo?','Não obrigatoriamente. O whey ajuda a atingir a proteína com praticidade, mas dá para bater a meta só com comida se a rotina permitir.'),
         ('Creatina é segura para iniciantes?','Sim. A creatina é um dos suplementos mais estudados e seguros, com benefícios de força e desempenho, inclusive para quem está começando.'),
         ('Pré-treino é necessário?','Para a maioria, não. A cafeína pode ajudar na disposição, mas fórmulas caras de pré-treino raramente fazem diferença real para iniciantes.')]},

 {'slug':'cafeina-pre-treino','read':6,'cat':'esportiva','badge':'Ergogênico de verdade',
  'title':'Cafeína antes do treino: ajuda mesmo?',
  'desc':'A cafeína é um dos poucos estimulantes com efeito comprovado no treino. Veja como usar, quanto e quais cuidados tomar.',
  'lead':'Entre tantos pré-treinos do mercado, a cafeína é um dos poucos ingredientes com efeito realmente comprovado no desempenho. Usada com bom senso, ela pode dar aquele empurrão na disposição e no rendimento.',
  'body':[
    ('h2','Por que a cafeína ajuda'),
    ('p','A cafeína reduz a percepção de esforço e de cansaço, o que faz o treino parecer menos pesado. Ela também melhora foco e disposição, e por isso é considerada um recurso ergogênico, ou seja, que favorece o desempenho.'),
    ('quote','A cafeína não dá força que você não tem, mas ajuda você a usar melhor a força que já tem.'),
    ('h2','Como usar bem'),
    ('h3','Quantidade e timing'),
    ('p','O efeito costuma aparecer com doses moderadas consumidas cerca de 30 a 60 minutos antes do treino. Café, alguns suplementos e até chás podem ser fontes. Mais não é melhor: doses altas trazem efeitos indesejados.'),
    ('h3','Cuidados'),
    ('p','Excesso de cafeína pode causar taquicardia, ansiedade, tremores e prejudicar o sono se consumida tarde. Pessoas mais sensíveis e quem tem questões cardíacas devem ter atenção redobrada.'),
    ('keybox','Cafeína pré-treino com segurança',['Usar doses moderadas, sem exagerar na busca por mais efeito.','Consumir cerca de 30 a 60 minutos antes do treino.','Evitar cafeína no fim do dia para não prejudicar o sono.','Observar a própria sensibilidade e tolerância.','Ter cautela em caso de questões cardíacas ou muita ansiedade.']),
    ('h2','Nem todo mundo precisa'),
    ('p','A cafeína é útil, mas não é obrigatória, e quem dorme mal ou é muito sensível pode se dar melhor sem ela. Um acompanhamento ajuda a definir se e como usar, de acordo com o seu treino e a sua saúde.'),
  ],
  'faq':[('Qual a melhor hora de tomar cafeína antes do treino?','Em geral entre 30 e 60 minutos antes, quando o efeito atinge o pico. Vale testar o que funciona melhor para você.'),
         ('Café serve como pré-treino?','Sim. O café é uma fonte prática de cafeína e pode cumprir bem esse papel, sem precisar de fórmulas caras.'),
         ('Cafeína atrapalha o sono?','Pode atrapalhar se consumida muitas horas depois, principalmente em pessoas sensíveis. Melhor concentrar o uso na primeira parte do dia.')]},

 {'slug':'massa-magra-mulher','read':7,'cat':'esportiva','badge':'Sem medo do peso',
  'title':'Ganho de massa magra para mulheres: por onde começar',
  'desc':'Ganhar massa magra deixa o corpo mais firme e saudável, sem virar fisiculturista. Veja como as mulheres devem começar.',
  'lead':'Muitas mulheres ainda evitam a musculação com medo de ficar musculosas demais. Na prática, ganhar massa magra deixa o corpo mais firme, forte e saudável, e é um dos melhores investimentos para a saúde a longo prazo.',
  'body':[
    ('h2','Por que ganhar massa magra'),
    ('p','Mais massa muscular melhora a força, a postura, a saúde óssea e o metabolismo. Também ajuda no emagrecimento, já que o músculo gasta mais energia. E não, a mulher não fica musculosa por acaso: isso exige anos de treino específico.'),
    ('quote','Musculação não deixa a mulher grande, deixa a mulher forte. O medo do peso costuma atrapalhar mais do que o peso em si.'),
    ('h2','Os dois pilares'),
    ('h3','Treino de força'),
    ('p','A musculação é o estímulo principal. Treinar com carga progressiva, respeitando a técnica e a evolução, é o que constrói músculo. Consistência ao longo dos meses importa mais do que treinos perfeitos e esporádicos.'),
    ('h3','Proteína e energia'),
    ('p','Sem proteína suficiente e energia adequada, o corpo não constrói músculo. Distribuir boas fontes de proteína ao longo do dia e não viver em restrição severa é essencial para os ganhos.'),
    ('keybox','Para começar a ganhar massa magra',['Incluir musculação com carga progressiva na rotina.','Garantir proteína suficiente e bem distribuída no dia.','Não viver em dieta muito restritiva o tempo todo.','Cuidar do sono, que é quando o músculo se recupera.','Ter paciência: ganho de massa é processo de meses.']),
    ('h2','Cada corpo no seu ritmo'),
    ('p','O ganho de massa magra é gradual e varia conforme genética, treino e alimentação. Um plano individualizado ajusta a proteína e as calorias ao seu objetivo, para você evoluir com saúde e sem excessos.'),
  ],
  'faq':[('Musculação deixa a mulher masculinizada?','Não. Ganhar volume muscular expressivo exige anos de treino e condições específicas. Para a maioria, o resultado é um corpo mais firme e forte.'),
         ('Preciso comer muito para ganhar massa?','Não é comer demais, é comer o suficiente, com proteína adequada e energia para o treino. Restrição severa atrapalha os ganhos.'),
         ('Dá para ganhar massa e emagrecer ao mesmo tempo?','É possível em algumas situações, principalmente para iniciantes, mas costuma ser mais lento. A estratégia depende do ponto de partida.')]},

 {'slug':'queda-de-cabelo-nutrientes','read':7,'cat':'saude','badge':'A raiz do problema',
  'title':'Queda de cabelo: quais nutrientes podem estar faltando',
  'desc':'A queda de cabelo pode ter relação com a alimentação. Veja quais nutrientes influenciam e quando investigar a causa.',
  'lead':'Notar mais fios no travesseiro ou no ralo do banho assusta, e é comum a alimentação ter alguma relação com isso. Alguns nutrientes são importantes para a saúde dos fios, e a falta deles pode contribuir para a queda.',
  'body':[
    ('h2','A alimentação influencia os fios'),
    ('p','O cabelo depende de proteína, ferro, zinco, biotina e outras vitaminas para crescer forte. Dietas muito restritivas, perda de peso rápida e deficiências nutricionais estão entre as causas alimentares de queda mais comuns.'),
    ('quote','O cabelo é um dos primeiros a sentir quando a alimentação está deficiente, porque o corpo o trata como prioridade menor.'),
    ('h2','Nutrientes que fazem diferença'),
    ('h3','Os principais'),
    ('p','O ferro tem papel importante, principalmente em mulheres com fluxo menstrual intenso. Proteína suficiente, zinco, vitamina D e do complexo B também sustentam o crescimento saudável dos fios.'),
    ('h3','Cuidado com os exageros'),
    ('p','Suplementar por conta própria nem sempre resolve e pode até fazer mal. O excesso de alguns nutrientes também é prejudicial. O ideal é identificar o que realmente falta antes de suplementar.'),
    ('keybox','Para fios mais saudáveis',['Garantir proteína suficiente ao longo do dia.','Cuidar dos níveis de ferro, sobretudo nas mulheres.','Evitar dietas muito restritivas e perda de peso brusca.','Variar a alimentação para cobrir vitaminas e minerais.','Investigar a causa antes de sair suplementando.']),
    ('h2','Nem toda queda é alimentar'),
    ('p','A queda de cabelo pode ter causas hormonais, genéticas, estresse ou pós-parto, então nem sempre a solução está no prato. Um acompanhamento médico e nutricional ajuda a identificar a causa e corrigir eventuais deficiências.'),
  ],
  'faq':[('Falta de ferro causa queda de cabelo?','Pode contribuir, principalmente em mulheres com anemia ou ferro baixo. Corrigir os níveis costuma ajudar na recuperação dos fios.'),
         ('Suplemento de biotina resolve a queda?','Só ajuda quem tem deficiência, o que não é comum. Para a maioria, tomar biotina por conta própria não faz diferença real.'),
         ('Dieta para emagrecer pode causar queda?','Sim, dietas muito restritivas e perda de peso rápida podem provocar queda por falta de nutrientes e energia. Emagrecer com equilíbrio protege os fios.')]},

 {'slug':'anemia-mulher-cansaco','read':7,'cat':'saude','badge':'Cansaço tem causa',
  'title':'Anemia na mulher: o cansaço que pode ser falta de ferro',
  'desc':'Cansaço, palidez e queda de cabelo podem indicar anemia por falta de ferro, comum em mulheres. Veja o que ajuda.',
  'lead':'Cansaço constante, falta de disposição, palidez e queda de cabelo são queixas comuns entre as mulheres, e muitas vezes por trás delas está a anemia por falta de ferro. A alimentação tem papel importante tanto na causa quanto na recuperação.',
  'body':[
    ('h2','Por que as mulheres são mais afetadas'),
    ('p','A perda de sangue na menstruação, principalmente em fluxos intensos, aumenta a necessidade de ferro. Gestação, dietas restritivas e baixa ingestão de alimentos ricos em ferro também favorecem a anemia nas mulheres.'),
    ('quote','Cansaço que não passa com descanso merece investigação. Muitas vezes é o ferro pedindo atenção.'),
    ('h2','O ferro na alimentação'),
    ('h3','Onde encontrar'),
    ('p','O ferro de melhor absorção vem de carnes, aves e peixes. Feijões, lentilha, grão-de-bico e vegetais verde-escuros também têm ferro, e combinar com vitamina C, como frutas cítricas, melhora bastante a absorção.'),
    ('h3','O que atrapalha'),
    ('p','Café e chá junto das refeições reduzem a absorção do ferro dos vegetais. Vale deixar essas bebidas para outros momentos do dia, longe das principais refeições.'),
    ('keybox','Para prevenir a anemia por ferro',['Incluir boas fontes de ferro nas refeições.','Combinar vegetais ricos em ferro com vitamina C.','Evitar café e chá junto das refeições principais.','Ficar atenta a fluxos menstruais muito intensos.','Investigar cansaço persistente com exames.']),
    ('h2','Alimentação e exames juntos'),
    ('p','A anemia precisa de diagnóstico por exames, e em alguns casos a alimentação sozinha não resolve, sendo necessária suplementação orientada. Um acompanhamento médico e nutricional identifica a causa e conduz a recuperação com segurança.'),
  ],
  'faq':[('Cansaço sempre é anemia?','Nem sempre. O cansaço tem várias causas, mas quando é persistente vale investigar anemia e outras questões com exames.'),
         ('Dá para tratar anemia só com comida?','Casos leves podem melhorar com alimentação, mas muitos precisam de suplementação orientada. O diagnóstico e o acompanhamento definem a conduta.'),
         ('Beterraba cura anemia?','Não. A beterraba tem pouco ferro e esse mito é comum. As melhores fontes são carnes, e entre os vegetais, feijões e folhas verde-escuras combinados com vitamina C.')]},

 {'slug':'acucar-antes-dos-2-anos','read':6,'cat':'materno','badge':'Paladar em formação',
  'title':'Por que evitar açúcar antes dos 2 anos',
  'desc':'Adiar o açúcar nos primeiros anos protege a saúde e o paladar do bebê. Entenda o porquê e como colocar isso na prática.',
  'lead':'Uma das recomendações mais importantes da alimentação infantil também é uma das mais difíceis de seguir: evitar açúcar antes dos 2 anos. Esse cuidado protege a saúde da criança e molda o paladar dela para a vida toda.',
  'body':[
    ('h2','Por que o açúcar é um problema tão cedo'),
    ('p','Nos primeiros anos, o paladar está em formação. Oferecer açúcar cedo acostuma a criança ao sabor muito doce, faz com que ela rejeite alimentos naturais e favorece cáries, ganho de peso e preferência por ultraprocessados.'),
    ('quote','Bebê não sente falta de açúcar, quem oferece somos nós. Adiar esse contato é um presente para o paladar dele.'),
    ('h2','Onde o açúcar se esconde'),
    ('h3','Fique atento aos rótulos'),
    ('p','Além do açúcar de mesa, ele aparece em bolachas, achocolatados, iogurtes adoçados, papinhas industrializadas, sucos de caixinha e muitos produtos vendidos como infantis. Ler o rótulo ajuda a identificar esses itens.'),
    ('h3','O doce natural das frutas'),
    ('p','A fruta é a melhor forma de oferecer sabor doce ao bebê, com fibras e nutrientes. Não é preciso adoçar papas nem sucos, e o ideal é priorizar a fruta inteira em vez de suco.'),
    ('keybox','Para adiar o açúcar com tranquilidade',['Não adoçar papas, mingaus, iogurtes nem sucos do bebê.','Oferecer frutas para satisfazer o gosto pelo doce.','Ler rótulos e evitar produtos com açúcar adicionado.','Segurar bolos e doces em festas no primeiro ano.','Dar o exemplo, já que a criança aprende observando.']),
    ('h2','Um cuidado que dura a vida toda'),
    ('p','Quanto mais tarde o açúcar entra, melhor a relação da criança com a comida de verdade. Cada família tem seus desafios, e um acompanhamento nutricional ajuda a colocar essa recomendação em prática sem virar um sofrimento.'),
  ],
  'faq':[('Pode dar um pouquinho de açúcar antes dos 2 anos?','A recomendação é evitar ao máximo. Não é sobre proibir de forma radical, mas quanto menos contato com açúcar nessa fase, melhor para o paladar e a saúde.'),
         ('Fruta tem açúcar, também devo evitar?','Não. O açúcar natural da fruta vem com fibras e nutrientes e é a forma ideal de oferecer o sabor doce. O que se evita é o açúcar adicionado.'),
         ('Mel pode no lugar do açúcar?','Não. Mel não é indicado antes de 1 ano pelo risco de botulismo, e depois disso continua sendo açúcar. O melhor é não acostumar com o doce.')]},

 {'slug':'engasgo-bebe-introducao','read':7,'cat':'materno','badge':'Segurança primeiro',
  'title':'Como evitar engasgo na introdução alimentar',
  'desc':'O medo do engasgo trava muitas famílias na introdução alimentar. Veja como oferecer os alimentos com mais segurança.',
  'lead':'O medo do engasgo é um dos que mais assustam na introdução alimentar, e faz muitas famílias adiarem os alimentos sólidos. Com alguns cuidados simples, dá para oferecer comida ao bebê com muito mais segurança e tranquilidade.',
  'body':[
    ('h2','Engasgo e ânsia não são a mesma coisa'),
    ('p','É importante diferenciar a ânsia (gag reflex) do engasgo. A ânsia é um reflexo protetor, comum e barulhento, em que o bebê traz a comida para frente. O engasgo verdadeiro é silencioso e obstrui a respiração, e aí sim exige ação imediata.'),
    ('quote','A ânsia faz barulho e assusta, mas é o corpo do bebê aprendendo. O engasgo perigoso costuma ser silencioso.'),
    ('h2','Cuidados que reduzem o risco'),
    ('h3','Como oferecer'),
    ('p','O bebê deve comer sempre sentado, com a coluna ereta, nunca deitado ou distraído. Os alimentos precisam ter textura e formato adequados à fase, bem cozidos e amassados ou em tiras firmes, conforme o método escolhido.'),
    ('h3','Alimentos de maior risco'),
    ('p','Uva inteira, tomate cereja, salsicha em rodela, castanhas inteiras, pipoca e pedaços duros e redondos oferecem mais risco. Eles devem ser evitados ou oferecidos cortados e preparados de forma segura.'),
    ('keybox','Para uma introdução mais segura',['Oferecer a comida sempre com o bebê sentado e ereto.','Nunca alimentar o bebê distraído, deitado ou no carro em movimento.','Adaptar textura e formato dos alimentos à fase.','Evitar alimentos redondos, duros e escorregadios inteiros.','Fazer um curso de primeiros socorros para bebês.']),
    ('h2','Preparo traz tranquilidade'),
    ('p','Conhecer os cuidados e aprender a manobra de desengasgo dá segurança para a família aproveitar a introdução alimentar. Um acompanhamento ajuda a escolher texturas e alimentos adequados para cada fase do bebê.'),
  ],
  'faq':[('Qual a diferença entre engasgo e ânsia?','A ânsia é um reflexo normal e barulhento que protege o bebê. O engasgo verdadeiro obstrui a respiração e costuma ser silencioso, exigindo ação imediata.'),
         ('Método BLW aumenta o risco de engasgo?','Estudos mostram que, feito com orientação e cuidados de segurança, o BLW não aumenta o risco de engasgo em relação à papa.'),
         ('Preciso saber primeiros socorros?','É altamente recomendado. Conhecer a manobra de desengasgo para bebês dá segurança e pode ser fundamental em qualquer método de introdução alimentar.')]},
]
